### ISSUE TITLE
assessing collection details

### ISSUE THREAD

**Issue by bwprice** [FabianDeister/Library_curation_BOLD#10]
these are the relevant fields, **bold** is my suggestion to score 1 if data present:
- **`collectors`**
- **`collection_date`**
- **Country/Ocean => `country`?**
- `province`
- `region`
- `sector`
- **Exact Site => `site`?**
- **Lat/Lon (don't need to score Lon if Lat present) => `coord`?**
- `elev`
- `depth`
- `elev_accuracy`
- `depth_accuracy`
- `coord_source`
- `coord_accuracy`
- Event Time => `collection_time`?
- `collection_date_accuracy`
- `habitat`
- Sampling Protocol
- `collection_note`
- Site Code
- Collection Event ID

This gives us a maximum score of 5, and a grading system 0 -> 5.

[COLL_DETAILS.pm](https://github.com/FabianDeister/Library_curation_BOLD/blob/main/lib/BCDM/Criteria/COLL_DETAILS.pm)

**Comment by rvosa** [comment]
Bouncing this back to @bwprice to refine the original issue. The following topics need clarification for the mapping:

- [ ] do the columns indicated in fixed width type indeed correspond to those in the dump (probably yes)
- [ ] do the columns with question marks correspond to this in the dump (maybe yes)
- [ ] what about the others? Doesn't appear to be a sensible mapping to the BCDM

Subsequent to that, what's the decision tree for treating these?

- [ ] we can score whether any of these fields has any data
- [ ] how to rank/adjudicate different patterns of presence/absence of data

**Comment by bwprice** [comment]
yes, @rvosa your mapping is correct, those unmapped fields aren't in the public data and don't matter anyway.

We decided in the meeting that `site` AND `collection_date` were needed for rank 2 (both present) whereas for rank 3 (only `site` present). No requirements for ranks 4 onwards.

**Comment by rvosa** [comment]
Let's assume we grade this and [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging) me through the logic.
- if site AND collection_date => rank 2
- if site AND NOT collection_date => rank 3
- what else...? The columns in the first post need to have data somewhere? Only the bold ones?

**Comment by bwprice** [comment]
I think based on yesterday's call that we just use `site` and `collection_date` as you've specified above. The rest can be ignored for now..

**Comment by bwprice** [comment]
without wanting to open a can of worms (again) I think we complicated it too much by treating this as a single entity. Why not just have pass / fail for each of:
`collectors`
`collection_date`
`country`
`site`
`coord`

We can then figure out how turning these off/on impact the results.

**Comment by rvosa** [comment]
Now exist as separate modules COLLECTORS.pm, COLLECTION_DATE.pm, COUNTRY.pm, SITE.pm and COORD.pm
