### ISSUE TITLE
IDENTIFIER - Specimen was identified by a named person

### ISSUE THREAD

**Issue by rvosa** [FabianDeister/Library_curation_BOLD#16]
For this criterion, the basic logic is that there should be a person named in the `identified_by` field but that this person should not be an employee of CBG (except, presumably, Paul Hebert). For this we need to have some list of people to ignore. A reasonable approach might be to start by checking the most common identifiers to see where they work. @bwprice, I vaguely recall you've taken a first stab at this?

**Comment by rvosa** [comment]
[Here](https://github.com/FabianDeister/Library_curation_BOLD/files/14421474/identifiers.csv) is the list so far, which was generated with:

```{sql}
SELECT identified_by, COUNT(*) AS occurrences
FROM bold
GROUP BY identified_by
ORDER BY occurrences DESC;
```

**Comment by bwprice** [comment]
most common people listed below, we should check some of the bold people (iBOL employees) as they also have tax expertise so probably shouldn't just cut them out:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/benjp/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/benjp/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


name | number
-- | --
**Kate Perez** | 291038
**Angela Telfer** | 110031
**Valerie Levesque-Beaudin** | 30377
**Gergin A. Blagoev** | 26543
Peter Huemer | 18478
**BOLD ID Engine** | 15923
Frank Koehler | 15378
Marko Mutanen | 15061
Renee Miskie | 13693
**Paul Hebert** | 11776
Mikko Pentinsaari | 11682
Axel Hausmann | 11340



</body>

</html>

**Comment by rvosa** [comment]
Great, thanks. Let's go with this as a first pass, tough I'd vote to keep Paul as an expert 😅

**Comment by bwprice** [comment]
I think the top 2 + BOLD ID Engine can be left off.
