### ISSUE TITLE
pipelining and WorkFlowHub

### ISSUE THREAD

**Issue by rvosa** [FabianDeister/Library_curation_BOLD#3]
To incorporate the scripts in a snakemake pipeline, a Snakefile needs to be added to the workflow/ directory. This way, commands can be chained in various orders and with externally configurable inputs and outputs. This directory layout complies with the submission guidelines of WorkFlowHub.

**Comment by rvosa** [comment]
The pipeline would consist of the following steps:

1. load_bcdm.pl - this loads the TSV dump from BOLD into a SQLite database. The step also involves first creating the database schema, which the Perl script does by applying schema.sql to the database. How the Perl script is run is documented in make_db.sh [here](https://github.com/FabianDeister/Library_curation_BOLD/blob/main/workflow/scripts/make_db.sh#L15-L20)
2. sqlite3 - it is a common practice when populating a database to first load the data, and only then compute the indexes (for performance). This is done by applying indexes.sql to the database, as documented [here](https://github.com/FabianDeister/Library_curation_BOLD/blob/main/workflow/scripts/make_db.sh#L28)
3. dbicdump - this is no longer needed, but for reference: the ORM modules that allow the Perl code to fiddle with the data objects directly was generated with the dbicdump tool, as shown [here](https://github.com/FabianDeister/Library_curation_BOLD/blob/main/workflow/scripts/make_db.sh#L34)
4. load_taxonomy.pl - the BOLD TSV dump is denormalized wrt the taxonomy, so it is good practice for data integrity and query performance to normalize the taxonomy in a separate table. This is done [here](https://github.com/FabianDeister/Library_curation_BOLD/blob/main/workflow/scripts/make_db.sh#L38)
5. load_targetlist.pl - here the BOLD taxonomy is cross-referenced with the target list. Assuming that #7 is solved, this flags in the database which species are in the target list
6. assess_criteria.pl - this does the actual curation. So, if all the previous steps are done and there is a coherent SQLite database, this task can be run multiple times, e.g. for different criteria.

Because there is no parallelization, the pipeline would be relatively straightforward to construct. The main thing to keep in mind is that snakemake cannot handle the situation where multiple steps have the same input and/or output (i.e. the database file) because it looks at the timestamp on the file to decide whether to rerun a step. The trick lies in creating separate files that flag that a step has been run, for example by creating a 0-byte file `load_bcdm.ok` or something like it.

**Comment by rvosa** [comment]
(BTW: it would also be possible to parallelize the assessment of the different criteria. Optionally, they can be written to TSV files instead of being persisted in the database. So you could run those on separate HPC nodes, and then merge them into the database.)

**Comment by FabianDeister** [comment]
we have snakemake now. The output does not work perfectly by now but I think that's something we can fix together quick

**Comment by rvosa** [comment]
I think we are far enough along on this to close the ticket. There's a snapshot here: https://workflowhub.eu/workflows/833

We just need to post salient new versions there when they come out.
