### ISSUE TITLE
INSTITUTION fails for all entries

### ISSUE THREAD

**Issue by bwprice** [FabianDeister/Library_curation_BOLD#30]
the check of [INSTITUTION](https://github.com/FabianDeister/Library_curation_BOLD/blob/main/lib/BCDM/Criteria/INSTITUTION.pm) should match a negative pattern, but everything is failing including records that don't match the pattern....

**Comment by rvosa** [comment]
We are now getting 1's and 0's in the output, so presumably this particular issue is fixed.
