### ISSUE TITLE
criteria not loaded for Country Type specimen and Seq quality

### ISSUE THREAD

**Issue by FabianDeister** [FabianDeister/Library_curation_BOLD#31]
the logfile of the three criteria look like this
Use of uninitialized value in pattern match (m//) at lib/BCDM/Criteria/TYPE_SPECIMEN.pm line 40.
Use of uninitialized value in pattern match (m//) at lib/BCDM/Criteria/TYPE_SPECIMEN.pm line 40.
Use of uninitialized value in pattern match (m//) at lib/BCDM/Criteria/TYPE_SPECIMEN.pm line 40.
Use of uninitialized value in pattern match (m//) at lib/BCDM/Criteria/TYPE_SPECIMEN.pm line 40.
Use of uninitialized value in pattern match (m//) at lib/BCDM/Criteria/TYPE_SPECIMEN.pm line 40.
Use of uninitialized value in pattern match (m//) at lib/BCDM/Criteria/TYPE_SPECIMEN.pm line 40.
Use of uninitialized value in pattern match (m//) at lib/BCDM/Criteria/TYPE_SPECIMEN.pm line 40.
Use of uninitialized value in pattern match (m//) at lib/BCDM/Criteria/TYPE_SPECIMEN.pm line 40.

**Comment by rvosa** [comment]
Fixed, no longer getting uninitialized warnings in the logs.
